version: "3.3"

services:
  traefik:
    image: traefik:v2.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
    networks:
      traefik:

networks:
  traefik:
    external:
      name: traefik