version: "3.3"

services:
  traefik:
    image: traefik:v2.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.prod.toml:/etc/traefik/traefik.toml"
      - "letsencrypt:/letsencrypt"
    networks:
      traefik:

volume:
  letsencrypt:

networks:
  traefik:
    external:
      name: traefik