version: "3.3"

services:
  traefik:
    image: traefik:v2.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.prod.toml:/etc/traefik/traefik.toml
      - letsencrypt:/letsencrypt
    networks:
      traefik:

volume:
  letsencrypt:

networks:
  traefik:
    external:
      name: traefik