version: "3.3"

services:
  traefik:
    image: traefik:v2.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.prod.toml:/etc/traefik/traefik.toml
    networks:
      traefik:

volumes:
  letsencrypt:

networks:
  traefik:
    external:
      name: traefik