name: Merged items

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  build-and-push-image:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: GITHUB_TOKEN
          script: |
            rm -R adr
            git clone git@github.com:TomBowyerResearchProject/adr.git
            cd adr
            ./scripts/start.sh prod yes