# NOTE: if you want to use github as opposed to my self hosted option for running test
# add a os in the matrix such as os: [ubuntu-latest] and then change runs-on to ${{ matrix.os }}
on: [push]
name: Lint and Test
jobs:
  full-run:
    strategy:
    runs-on: self-hosted
    steps:
    - name: Test Dev build
      run: make test_dev
    - name: Test prod build
      run: make test_prod